language: java

jdk:
    - openjdk8

services:
    - docker
    
env:
  DOCKER_COMPOSE_VERSION: 1.29.2 
    
before_script:
- cd ./docker/dev
- docker-compose up -d --build
- cd ..
- cd ../src

sript:
- mvn clean verify
- mvn test -Ptest-business

after_script:
- docker-compose down
